Repository hanshuaikang/Nping, pull requests merged in 2025-01, with the labels that each got.

#15 feat: release v0.2.0
  Cargo.lock
  Cargo.toml
  src/main.rs
Labels: enhancement

#16 docs: add star history
  README.md
  README_ZH.md
Labels: documentation

#22 feat: add homebrew formula
  Formula/nping.rb
Labels: documentation

#25 fix: increase the latency of the display
  src/network.rs
  src/ui.rs
Labels: bug

#28 feat: add release workflow
  .github/workflows/release.yml
Labels: documentation

#29 fix: typo
  src/main.rs
Labels: minor

#30 feat: support auto release windows
  .github/workflows/release.yml
Labels: minor

#46 feat: add self-media thanks
  README.md
  README_ZH.md
Labels: documentation

#45 feat: reconstructing channel implementation
  Cargo.lock
  Cargo.toml
  src/main.rs
  src/network.rs
  src/ui.rs
Labels: enhancement

#55 minor: optimize display effects
  src/main.rs
  src/ui.rs
Labels: enhancement
